from __future__ import annotations

import dataclasses
import json
import re
import urllib.error
import urllib.parse
import urllib.request
from typing import Any


API_VERSION = "2026-03-10"
MAX_SUBTASKS = 20
MAX_ISSUE_TITLE_LENGTH = 120
MAX_TASK_TITLE_LENGTH = 120
MAX_TEXT_FIELD_LENGTH = 5000

AF_EPIC_RE = re.compile(r"^AF-E-\d{4}$")
AF_ID_PART_RE = re.compile(r"^AF-E-(\d{4})$")
AF_ID_IN_TITLE_RE = re.compile(r"^\[(AF-E-\d{4})\]\s*(.+)$")
AF_IDEA_RE = re.compile(r"^AF-I-\d{4}$")
TASK_ID_RE = re.compile(r"^\[(AF-T-\d{4}\.\d+)\]")
GENERATED_MARKER_RE = re.compile(r"<!--\s*roadmap-automation:\s*generated=true\s+af_id=(AF-E-\d{4})\s*-->")

FIELD_LABELS = {
    "AF Epic ID": "af_id",
    "Related idea ID": "idea_id",
    "Related discussion URL": "discussion_url",
    "Area": "area",
    "Initial maturity": "maturity",
    "Size Points": "size_points",
    "Priority": "priority",
    "Target Release": "target_release",
    "Public roadmap bucket": "public_roadmap",
    "Summary": "summary",
    "Epic acceptance criteria": "acceptance_criteria",
    "Suggested subtasks": "tasks_text",
}

ALLOWED_AREAS = {
    "Storage",
    "GSN",
    "SACM",
    "Review",
    "AI",
    "UI",
    "Export",
    "Compliance",
    "Documentation",
    "Build / CI",
    "Other",
}
ALLOWED_MATURITY = {"Candidate", "Planned", "Prototype 1", "Prototype 2", "Ready", "Deferred"}
ALLOWED_SIZE_POINTS = {"1", "2", "3", "5", "8", "13", "21"}
ALLOWED_PRIORITY = {"Critical", "High", "Medium", "Low", "Later"}
ALLOWED_PUBLIC_ROADMAP = {"Now", "Next", "Later", "Not public yet"}
TRUSTED_ACTOR_PERMISSIONS = {"admin", "maintain", "write"}

AREA_LABELS = {
    "Storage": "area: storage",
    "GSN": "area: gsn",
    "SACM": "area: sacm",
    "Review": "area: review",
    "AI": "area: ai",
    "UI": "area: ui",
    "Export": "area: export",
    "Compliance": "area: compliance",
    "Documentation": "area: documentation",
    "Build / CI": "area: build-ci",
    "Other": "area: other",
}

LABEL_DEFINITIONS = {
    "roadmap-request": {"color": "1d76db", "description": "Roadmap epic request pending review"},
    "roadmap-approved": {"color": "0e8a16", "description": "Maintainer approved roadmap generation"},
    "roadmap-retry": {"color": "fbca04", "description": "Retry roadmap follow-up automation"},
    "roadmap-generated": {"color": "5319e7", "description": "Generated by roadmap automation"},
    "roadmap-failed": {"color": "b60205", "description": "Roadmap automation failed"},
    "needs-roadmap-review": {"color": "fbca04", "description": "Needs maintainer roadmap review"},
    "type: epic": {"color": "5319e7", "description": "Roadmap epic"},
    "type: task": {"color": "c5def5", "description": "Roadmap task"},
    "type: documentation": {"color": "0075ca", "description": "Documentation work"},
    "type: bug": {"color": "d73a4a", "description": "Bug report"},
    "type: feature": {"color": "a2eeef", "description": "Feature work"},
    "area: storage": {"color": "bfdadc", "description": "Storage area"},
    "area: gsn": {"color": "bfdadc", "description": "GSN area"},
    "area: sacm": {"color": "bfdadc", "description": "SACM area"},
    "area: review": {"color": "bfdadc", "description": "Review area"},
    "area: ai": {"color": "bfdadc", "description": "AI area"},
    "area: ui": {"color": "bfdadc", "description": "UI area"},
    "area: export": {"color": "bfdadc", "description": "Export area"},
    "area: compliance": {"color": "bfdadc", "description": "Compliance area"},
    "area: documentation": {"color": "bfdadc", "description": "Documentation area"},
    "area: build-ci": {"color": "bfdadc", "description": "Build and CI area"},
    "area: other": {"color": "bfdadc", "description": "Other roadmap area"},
}

PROJECT_FIELD_DEFINITIONS = {
    "AF ID": {"type": "Text", "data_type": "TEXT"},
    "Area": {"type": "Single select", "options": sorted(ALLOWED_AREAS)},
    "Maturity": {"type": "Single select", "options": sorted(ALLOWED_MATURITY)},
    "Size Points": {"type": "Number", "data_type": "NUMBER"},
    "Completed Points": {"type": "Number", "data_type": "NUMBER"},
    "Priority": {"type": "Single select", "options": sorted(ALLOWED_PRIORITY)},
    "Target Release": {"type": "Text or single select"},
    "Public Roadmap": {"type": "Single select", "options": sorted(ALLOWED_PUBLIC_ROADMAP)},
    "Discussion URL": {"type": "Text", "data_type": "TEXT"},
    "Automation Status": {"type": "Single select", "options": ["Generated"]},
}


@dataclasses.dataclass(frozen=True)
class RoadmapRequest:
    af_id: str
    idea_id: str
    discussion_url: str
    area: str
    maturity: str
    size_points: str
    priority: str
    target_release: str
    public_roadmap: str
    summary: str
    acceptance_criteria: str
    tasks: list[str]
    title: str


@dataclasses.dataclass
class GeneratedTask:
    task_id: str
    title: str
    issue_number: int | None = None
    issue_id: int | None = None
    node_id: str | None = None
    html_url: str | None = None


@dataclasses.dataclass(frozen=True)
class ValidationResult:
    errors: list[str]

    @property
    def ok(self) -> bool:
        return not self.errors


class GitHubApiError(RuntimeError):
    def __init__(self, status: int, message: str):
        super().__init__(f"GitHub API error {status}: {message}")
        self.status = status
        self.message = message


class GitHubClient:
    def __init__(self, repo: str, token: str):
        if "/" not in repo:
            raise ValueError("REPO must be in owner/name form")
        self.repo = repo
        self.owner, self.name = repo.split("/", 1)
        self.token = token
        self.rest_base_url = "https://api.github.com"
        self.graphql_url = "https://api.github.com/graphql"

    def _headers(self, token: str | None = None) -> dict[str, str]:
        headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": API_VERSION,
            "User-Agent": "assurance-forge-roadmap-automation",
        }
        actual_token = token or self.token
        if actual_token:
            headers["Authorization"] = f"Bearer {actual_token}"
        return headers

    def request(self, method: str, path: str, data: dict[str, Any] | None = None,
                expected: tuple[int, ...] = (200,), token: str | None = None) -> Any:
        body = None if data is None else json.dumps(data).encode("utf-8")
        request = urllib.request.Request(
            f"{self.rest_base_url}{path}",
            data=body,
            headers=self._headers(token),
            method=method,
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                response_body = response.read().decode("utf-8")
                if response.status not in expected:
                    raise GitHubApiError(response.status, response_body)
                if not response_body:
                    return None
                return json.loads(response_body)
        except urllib.error.HTTPError as error:
            message = error.read().decode("utf-8", errors="replace")
            try:
                parsed = json.loads(message)
                message = parsed.get("message", message)
            except json.JSONDecodeError:
                pass
            raise GitHubApiError(error.code, message) from error

    def graphql(self, query: str, variables: dict[str, Any] | None = None,
                token: str | None = None) -> dict[str, Any]:
        body = json.dumps({"query": query, "variables": variables or {}}).encode("utf-8")
        request = urllib.request.Request(
            self.graphql_url,
            data=body,
            headers=self._headers(token),
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                parsed = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as error:
            message = error.read().decode("utf-8", errors="replace")
            raise GitHubApiError(error.code, message) from error
        if parsed.get("errors"):
            messages = "; ".join(error.get("message", "GraphQL error") for error in parsed["errors"])
            raise GitHubApiError(400, messages)
        return parsed["data"]

    def paginated(self, path: str, token: str | None = None) -> list[dict[str, Any]]:
        separator = "&" if "?" in path else "?"
        page = 1
        results: list[dict[str, Any]] = []
        while True:
            page_path = f"{path}{separator}per_page=100&page={page}"
            items = self.request("GET", page_path, expected=(200,), token=token)
            if not items:
                return results
            results.extend(items)
            if len(items) < 100:
                return results
            page += 1

    def get_issue(self, issue_number: int) -> dict[str, Any]:
        return self.request("GET", f"/repos/{self.repo}/issues/{issue_number}")

    def get_actor_permission(self, username: str) -> str:
        if not username:
            return "none"
        encoded = urllib.parse.quote(username, safe="")
        try:
            data = self.request("GET", f"/repos/{self.repo}/collaborators/{encoded}/permission")
        except GitHubApiError as error:
            if error.status == 404:
                return "none"
            raise
        return str(data.get("permission") or "none").lower()

    def update_issue(self, issue_number: int, title: str | None = None, body: str | None = None,
                     labels: list[str] | None = None) -> dict[str, Any]:
        payload: dict[str, Any] = {}
        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        if labels is not None:
            payload["labels"] = labels
        return self.request("PATCH", f"/repos/{self.repo}/issues/{issue_number}", payload)

    def create_issue(self, title: str, body: str, labels: list[str]) -> dict[str, Any]:
        return self.request("POST", f"/repos/{self.repo}/issues", {"title": title, "body": body, "labels": labels}, expected=(201,))

    def create_comment(self, issue_number: int, body: str) -> None:
        self.request("POST", f"/repos/{self.repo}/issues/{issue_number}/comments", {"body": body}, expected=(201,))

    def add_labels(self, issue_number: int, labels: list[str]) -> None:
        if labels:
            self.request("POST", f"/repos/{self.repo}/issues/{issue_number}/labels", {"labels": labels}, expected=(200,))

    def remove_label(self, issue_number: int, label: str) -> None:
        encoded = urllib.parse.quote(label, safe="")
        try:
            self.request("DELETE", f"/repos/{self.repo}/issues/{issue_number}/labels/{encoded}", expected=(200, 204))
        except GitHubApiError as error:
            if error.status != 404:
                raise

    def ensure_label(self, name: str, color: str, description: str) -> None:
        encoded = urllib.parse.quote(name, safe="")
        try:
            self.request("GET", f"/repos/{self.repo}/labels/{encoded}")
        except GitHubApiError as error:
            if error.status != 404:
                raise
            self.request(
                "POST",
                f"/repos/{self.repo}/labels",
                {"name": name, "color": color, "description": description},
                expected=(201,),
            )

    def list_issues(self, labels: list[str] | None = None) -> list[dict[str, Any]]:
        path = f"/repos/{self.repo}/issues?state=all"
        if labels:
            path += "&labels=" + urllib.parse.quote(",".join(labels), safe="")
        return self.paginated(path)

    def list_sub_issues(self, issue_number: int) -> list[dict[str, Any]]:
        try:
            return self.paginated(f"/repos/{self.repo}/issues/{issue_number}/sub_issues")
        except GitHubApiError as error:
            if error.status in {404, 410}:
                return []
            raise

    def add_sub_issue(self, issue_number: int, sub_issue_id: int) -> None:
        self.request(
            "POST",
            f"/repos/{self.repo}/issues/{issue_number}/sub_issues",
            {"sub_issue_id": sub_issue_id},
            expected=(201,),
        )


def ensure_roadmap_labels(client: GitHubClient) -> None:
    for name, definition in LABEL_DEFINITIONS.items():
        client.ensure_label(name, definition["color"], definition["description"])


def issue_labels(issue: dict[str, Any]) -> list[str]:
    return [label["name"] for label in issue.get("labels", [])]


def is_roadmap_request_issue(issue: dict[str, Any]) -> bool:
    labels = issue_labels(issue)
    body = issue.get("body") or ""
    title = issue.get("title") or ""
    return "roadmap-request" in labels or title.startswith("[EPIC REQUEST]:") or "### AF Epic ID" in body


def clean_form_value(value: str) -> str:
    value = value.replace("\r\n", "\n").strip()
    if value in {"_No response_", "No response"}:
        return ""
    return value.replace("\x00", "")


def parse_issue_form(body: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    current_label: str | None = None
    buffer: list[str] = []
    for line in body.replace("\r\n", "\n").split("\n"):
        if line.startswith("### "):
            if current_label is not None:
                fields[current_label] = clean_form_value("\n".join(buffer))
            current_label = line[4:].strip()
            buffer = []
        elif current_label is not None:
            buffer.append(line)
    if current_label is not None:
        fields[current_label] = clean_form_value("\n".join(buffer))
    return {FIELD_LABELS[label]: value for label, value in fields.items() if label in FIELD_LABELS}


def normalize_task_title(line: str) -> str:
    title = line.strip()
    title = re.sub(r"^[-*+]\s+", "", title)
    title = re.sub(r"^\d+[.)]\s+", "", title)
    title = re.sub(r"^- \[[ xX]\]\s+", "", title)
    return title.strip()


def parse_tasks(tasks_text: str) -> list[str]:
    return [t for t in (normalize_task_title(line) for line in tasks_text.splitlines()) if t]


def extract_epic_title(issue_title: str, af_id: str = "") -> str:
    title = issue_title.strip()
    if title.startswith("[EPIC REQUEST]:"):
        return title.removeprefix("[EPIC REQUEST]:").strip()
    match = AF_ID_IN_TITLE_RE.match(title)
    if match:
        return match.group(2).strip()
    if af_id and title.startswith(f"[{af_id}]"):
        return title[len(af_id) + 2:].strip()
    return title


def build_request_from_issue(issue: dict[str, Any]) -> RoadmapRequest:
    fields = parse_issue_form(issue.get("body") or "")
    af_id = fields.get("af_id", "").strip()
    title = extract_epic_title(issue.get("title") or "", af_id)
    return RoadmapRequest(
        af_id=af_id,
        idea_id=fields.get("idea_id", "").strip(),
        discussion_url=fields.get("discussion_url", "").strip(),
        area=fields.get("area", "").strip(),
        maturity=fields.get("maturity", "").strip(),
        size_points=fields.get("size_points", "").strip(),
        priority=fields.get("priority", "").strip(),
        target_release=fields.get("target_release", "").strip(),
        public_roadmap=fields.get("public_roadmap", "").strip(),
        summary=fields.get("summary", "").strip(),
        acceptance_criteria=fields.get("acceptance_criteria", "").strip(),
        tasks=parse_tasks(fields.get("tasks_text", "")),
        title=title,
    )


def validate_request(request: RoadmapRequest, require_af_id: bool) -> ValidationResult:
    errors: list[str] = []
    if require_af_id and not request.af_id:
        errors.append("AF Epic ID is required before a maintainer approves generation.")
    if request.af_id and not AF_EPIC_RE.match(request.af_id):
        errors.append("AF Epic ID must use the AF-E-xxxx format.")
    if request.idea_id and not AF_IDEA_RE.match(request.idea_id):
        errors.append("Related idea ID must use the AF-I-xxxx format.")
    if request.discussion_url and not request.discussion_url.startswith(("https://", "http://")):
        errors.append("Related discussion URL must be an http or https URL.")
    if not request.title:
        errors.append("The issue title must include an epic title after the prefix.")
    if len(request.title) > MAX_ISSUE_TITLE_LENGTH:
        errors.append(f"Epic title must be {MAX_ISSUE_TITLE_LENGTH} characters or fewer.")
    if request.area not in ALLOWED_AREAS:
        errors.append("Area must match one of the issue form options.")
    if request.maturity not in ALLOWED_MATURITY:
        errors.append("Initial maturity must match one of the issue form options.")
    if request.size_points not in ALLOWED_SIZE_POINTS:
        errors.append("Size Points must be one of 1, 2, 3, 5, 8, 13, or 21.")
    if request.priority not in ALLOWED_PRIORITY:
        errors.append("Priority must match one of the issue form options.")
    if request.public_roadmap not in ALLOWED_PUBLIC_ROADMAP:
        errors.append("Public roadmap bucket must match one of the issue form options.")
    for field_name, field_value in {
        "Summary": request.summary,
        "Epic acceptance criteria": request.acceptance_criteria,
        "Target Release": request.target_release,
        "Related discussion URL": request.discussion_url,
    }.items():
        if len(field_value) > MAX_TEXT_FIELD_LENGTH:
            errors.append(f"{field_name} must be {MAX_TEXT_FIELD_LENGTH} characters or fewer.")
    if not request.summary:
        errors.append("Summary is required.")
    if not request.acceptance_criteria:
        errors.append("Epic acceptance criteria are required.")
    if not request.tasks:
        errors.append("At least one suggested subtask is required.")
    if len(request.tasks) > MAX_SUBTASKS:
        errors.append(f"No more than {MAX_SUBTASKS} subtasks may be generated.")
    seen_tasks: set[str] = set()
    for task in request.tasks:
        if len(task) > MAX_TASK_TITLE_LENGTH:
            errors.append(f"Task title is too long: {task[:40]}...")
        key = task.casefold()
        if key in seen_tasks:
            errors.append(f"Duplicate task title: {task}")
        seen_tasks.add(key)
    return ValidationResult(errors)


def is_trusted_actor_permission(permission: str) -> bool:
    return permission.lower() in TRUSTED_ACTOR_PERMISSIONS


def generated_marker_for(af_id: str) -> str:
    return f"<!-- roadmap-automation: generated=true af_id={af_id} -->"


def has_generated_marker(body: str) -> bool:
    return GENERATED_MARKER_RE.search(body or "") is not None


def generated_marker_af_id(body: str) -> str:
    match = GENERATED_MARKER_RE.search(body or "")
    return match.group(1) if match else ""


def task_id_prefix(af_id: str) -> str:
    match = AF_ID_PART_RE.match(af_id)
    if not match:
        raise ValueError("Invalid AF epic ID")
    return f"AF-T-{match.group(1)}"


def generate_tasks(af_id: str, task_titles: list[str]) -> list[GeneratedTask]:
    prefix = task_id_prefix(af_id)
    return [GeneratedTask(f"{prefix}.{index}", title) for index, title in enumerate(task_titles, start=1)]


def completion_fraction(maturity: str) -> float:
    return {"Prototype 1": 0.30, "Prototype 2": 0.70, "Ready": 1.00}.get(maturity, 0.0)


def completed_points(size_points: str, maturity: str) -> float:
    return float(size_points) * completion_fraction(maturity)


def format_points(value: float) -> str:
    if value.is_integer():
        return str(int(value))
    return f"{value:.1f}"


def area_label(area: str) -> str:
    return AREA_LABELS[area]


def markdown_table_value(value: str) -> str:
    clean = value.replace("|", "\\|").replace("\n", "<br>").strip()
    return clean if clean else "-"


def generated_task_checklist(tasks: list[GeneratedTask]) -> str:
    lines = []
    for task in tasks:
        suffix = f" #{task.issue_number}" if task.issue_number else ""
        lines.append(f"- [ ] {task.task_id} {task.title}{suffix}")
    return "\n".join(lines)


def render_epic_body(request: RoadmapRequest, tasks: list[GeneratedTask]) -> str:
    metadata = [
        ("AF ID", request.af_id),
        ("Related idea", request.idea_id),
        ("Area", request.area),
        ("Maturity", request.maturity),
        ("Size Points", request.size_points),
        ("Completed Points", format_points(completed_points(request.size_points, request.maturity))),
        ("Priority", request.priority),
        ("Target Release", request.target_release),
        ("Public Roadmap", request.public_roadmap),
    ]
    table = "\n".join(f"| {name} | {markdown_table_value(value)} |" for name, value in metadata)
    discussion = request.discussion_url or "-"
    return f"""# [{request.af_id}] {request.title}

{generated_marker_for(request.af_id)}

## Summary

{request.summary}

## Roadmap metadata

| Field | Value |
|---|---|
{table}

## Acceptance criteria

{request.acceptance_criteria}

## Generated subtasks

{generated_task_checklist(tasks)}

## Related discussion

{discussion}
"""


def render_task_body(request: RoadmapRequest, task: GeneratedTask, parent_issue_number: int) -> str:
    return f"""# [{task.task_id}] {task.title}

Parent epic: #{parent_issue_number}

## Purpose

This task contributes to the roadmap epic:

- [{request.af_id}] {request.title}

## Scope

{task.title}

## Acceptance criteria

- [ ] Implementation is complete.
- [ ] Relevant tests are added or updated.
- [ ] Documentation is updated if user-visible behavior changes.

<!-- roadmap-automation: generated=true parent={request.af_id} task={task.task_id} -->
"""


def section_between(body: str, start_heading: str, end_heading: str) -> str:
    normalized = body.replace("\r\n", "\n")
    start = normalized.find(start_heading)
    if start < 0:
        return ""
    start += len(start_heading)
    end = normalized.find(end_heading, start)
    if end < 0:
        end = len(normalized)
    return normalized[start:end].strip()


def generated_metadata(body: str) -> dict[str, str]:
    metadata: dict[str, str] = {}
    metadata_block = section_between(body, "## Roadmap metadata", "## Acceptance criteria")
    for line in metadata_block.splitlines():
        if not line.startswith("|") or "---" in line or "Field" in line:
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) >= 2:
            value = cells[1].replace("<br>", "\n").replace("\\|", "|")
            metadata[cells[0]] = "" if value == "-" else value
    return metadata


def build_request_from_generated_epic(issue: dict[str, Any]) -> RoadmapRequest:
    body = issue.get("body") or ""
    metadata = generated_metadata(body)
    af_id = metadata.get("AF ID") or generated_marker_af_id(body)
    return RoadmapRequest(
        af_id=af_id,
        idea_id=metadata.get("Related idea", ""),
        discussion_url=section_between(body, "## Related discussion", "## ").strip("-").strip(),
        area=metadata.get("Area", ""),
        maturity=metadata.get("Maturity", ""),
        size_points=metadata.get("Size Points", ""),
        priority=metadata.get("Priority", ""),
        target_release=metadata.get("Target Release", ""),
        public_roadmap=metadata.get("Public Roadmap", ""),
        summary=section_between(body, "## Summary", "## Roadmap metadata"),
        acceptance_criteria=section_between(body, "## Acceptance criteria", "## Generated subtasks"),
        tasks=[task.title for task in generated_tasks_from_epic_body(body)],
        title=extract_epic_title(issue.get("title") or "", af_id),
    )


def generated_tasks_from_epic_body(body: str) -> list[GeneratedTask]:
    tasks: list[GeneratedTask] = []
    subtasks_block = section_between(body, "## Generated subtasks", "## Related discussion")
    pattern = re.compile(r"^- \[[ xX]\]\s+(AF-T-\d{4}\.\d+)\s+(.+?)(?:\s+#(\d+))?$")
    for line in subtasks_block.splitlines():
        match = pattern.match(line.strip())
        if not match:
            continue
        title = match.group(2).strip()
        issue_number = int(match.group(3)) if match.group(3) else None
        tasks.append(GeneratedTask(match.group(1), title, issue_number=issue_number))
    return tasks


def validation_comment(result: ValidationResult) -> str:
    if result.ok:
        return (
            "Thanks for the roadmap request. This has been marked for maintainer review.\n\n"
            "A maintainer can approve generation by applying the `roadmap-approved` label."
        )
    errors = "\n".join(f"- {error}" for error in result.errors)
    return (
        "Thanks for the roadmap request. It needs a maintainer review before generation can run.\n\n"
        "The automation found these issues:\n\n"
        f"{errors}\n\n"
        "After the request is updated, a maintainer can apply `roadmap-approved` to generate the epic structure."
    )


def existing_tasks_by_id(issues: list[dict[str, Any]], expected_tasks: list[GeneratedTask]) -> dict[str, dict[str, Any]]:
    expected_ids = {task.task_id for task in expected_tasks}
    found: dict[str, dict[str, Any]] = {}
    for issue in issues:
        title = issue.get("title") or ""
        match = TASK_ID_RE.match(title)
        if match and match.group(1) in expected_ids and match.group(1) not in found:
            found[match.group(1)] = issue
    return found


def apply_issue_data_to_task(task: GeneratedTask, issue: dict[str, Any]) -> GeneratedTask:
    task.issue_number = issue.get("number")
    task.issue_id = issue.get("id")
    task.node_id = issue.get("node_id")
    task.html_url = issue.get("html_url")
    return task


def resolve_project_id(client: GitHubClient, owner: str, project_number: str, token: str) -> str:
    number = int(project_number)
    errors: list[str] = []
    for owner_type in ("user", "organization"):
        query = f"""
        query($owner: String!, $number: Int!) {{
          {owner_type}(login: $owner) {{ projectV2(number: $number) {{ id }} }}
        }}
        """
        try:
            data = client.graphql(query, {"owner": owner, "number": number}, token=token)
        except GitHubApiError as error:
            errors.append(f"{owner_type} lookup failed: {error.message}")
            continue
        project_owner = data.get(owner_type)
        project = project_owner and project_owner.get("projectV2")
        if project:
            return project["id"]
        errors.append(f"{owner_type} lookup found no ProjectV2 number {project_number}")
    detail = " ".join(errors)
    raise GitHubApiError(
        404,
        f"Project {owner}/{project_number} was not found. {detail} "
        "Check ROADMAP_PROJECT_OWNER and ROADMAP_PROJECT_NUMBER. "
        "ROADMAP_PROJECT_NUMBER must be the number from a user or organization Project URL, "
        "such as https://github.com/users/OWNER/projects/NUMBER or https://github.com/orgs/OWNER/projects/NUMBER. "
        "If that URL is correct, the token used by the workflow probably cannot access the Project; "
        "add a ROADMAP_TOKEN secret with access to the repository issues and the target Project.",
    )


def project_fields(client: GitHubClient, project_id: str, token: str) -> dict[str, dict[str, Any]]:
    query = """
    query($projectId: ID!) {
      node(id: $projectId) {
        ... on ProjectV2 {
          fields(first: 100) {
            nodes {
              __typename
              ... on ProjectV2FieldCommon { id name }
              ... on ProjectV2Field { id name dataType }
              ... on ProjectV2SingleSelectField { id name options { id name } }
            }
          }
        }
      }
    }
    """
    data = client.graphql(query, {"projectId": project_id}, token=token)
    nodes = data["node"]["fields"]["nodes"]
    return {field["name"]: field for field in nodes if field and field.get("name")}


def add_project_item(client: GitHubClient, project_id: str, content_id: str, token: str) -> str:
    mutation = """
    mutation($projectId: ID!, $contentId: ID!) {
      addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) { item { id } }
    }
    """
    data = client.graphql(mutation, {"projectId": project_id, "contentId": content_id}, token=token)
    return data["addProjectV2ItemById"]["item"]["id"]


def update_project_field(client: GitHubClient, project_id: str, item_id: str, field: dict[str, Any], value: Any,
                         token: str) -> None:
    if value in {None, ""}:
        return
    field_type = field.get("__typename")
    value_payload: dict[str, Any]
    if field_type == "ProjectV2SingleSelectField":
        option = next((option for option in field.get("options", []) if option.get("name") == value), None)
        if not option:
            raise GitHubApiError(400, f"Project field {field['name']} has no option named {value}")
        value_payload = {"singleSelectOptionId": option["id"]}
    elif field.get("name") in {"Size Points", "Completed Points"}:
        value_payload = {"number": float(value)}
    else:
        value_payload = {"text": str(value)}
    mutation = """
    mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
      updateProjectV2ItemFieldValue(input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: $value}) {
        projectV2Item { id }
      }
    }
    """
    client.graphql(
        mutation,
        {"projectId": project_id, "itemId": item_id, "fieldId": field["id"], "value": value_payload},
        token=token,
    )


def project_field_setup_warning(name: str, field: dict[str, Any] | None, value: Any) -> str:
    definition = PROJECT_FIELD_DEFINITIONS.get(name, {"type": "Text"})
    expected_type = definition["type"]
    if not field:
        options = definition.get("options")
        option_text = f" with options: {', '.join(options)}" if options else ""
        return f"Project field `{name}` is missing. Create a {expected_type} field named exactly `{name}`{option_text}."

    field_type = field.get("__typename")
    single_select_allowed = expected_type in {"Single select", "Text or single select"}
    if field_type == "ProjectV2SingleSelectField" and not single_select_allowed:
        return (
            f"Project field `{name}` should be a {expected_type} field. "
            "Current field type is Single select."
        )
    if expected_type == "Single select" and field_type != "ProjectV2SingleSelectField":
        options = definition.get("options", [])
        return (
            f"Project field `{name}` should be a Single select field with options: {', '.join(options)}. "
            f"Current field type is {field_type or 'unknown'}."
        )
    expected_data_type = definition.get("data_type")
    actual_data_type = field.get("dataType")
    if expected_data_type and actual_data_type and actual_data_type != expected_data_type:
        return (
            f"Project field `{name}` should be a {expected_type} field. "
            f"Current Project data type is {actual_data_type}."
        )
    if field_type == "ProjectV2SingleSelectField" and value not in {None, ""}:
        option = next((option for option in field.get("options", []) if option.get("name") == value), None)
        if not option:
            return f"Project field `{name}` has no option named `{value}`. Add that option to the single-select field."
    return ""


def set_project_fields(client: GitHubClient, project_id: str, item_id: str, fields: dict[str, dict[str, Any]],
                       values: dict[str, Any], token: str) -> list[str]:
    warnings: list[str] = []
    for name, value in values.items():
        field = fields.get(name)
        warning = project_field_setup_warning(name, field, value)
        if warning:
            warnings.append(warning)
            continue
        if value in {None, ""}:
            continue
        update_project_field(client, project_id, item_id, field, value, token)
    return warnings


def project_values_for_request(request: RoadmapRequest, af_id: str, include_points: bool) -> dict[str, Any]:
    values: dict[str, Any] = {
        "AF ID": af_id,
        "Area": request.area,
        "Maturity": request.maturity,
        "Priority": request.priority,
        "Target Release": request.target_release,
        "Public Roadmap": request.public_roadmap,
        "Discussion URL": request.discussion_url,
        "Automation Status": "Generated",
    }
    if include_points:
        values["Size Points"] = float(request.size_points)
        values["Completed Points"] = completed_points(request.size_points, request.maturity)
    return values