#pragma once

#include "core/commands/command_bus.h"
#include "parser/xml_parser.h"

#include <nlohmann/json.hpp>

#include <string>

// Audited commands that mutate ACP (Assurance Claim Point) records. ACP editing
// previously bypassed the command bus (unaudited, writing the legacy package
// directly); these commands route it through the same library-primary bridge
// chokepoint every other audited mutation uses (`ApplyLibraryPrimaryOrLegacy`),
// so an ACP add/remove/upsert becomes a recorded, replayable transaction.
//
// Determinism: AddAcp generates a deterministic ACP<n> id on first apply, which
// is captured into the payload; replay forces it via `core::acp::AddAcpWithId`.
// Remove/Upsert already take explicit ids.
namespace core::commands {

// JSON (de)serialization for a parser::AcpRecord audit payload. No serializer
// existed elsewhere (reviews/proposal serialize their own POD types), so these
// are the canonical form the UpsertAcp event round-trips through.
nlohmann::ordered_json SerializeAcpRecord(const parser::AcpRecord& acp);
bool DeserializeAcpRecord(const nlohmann::ordered_json& json, parser::AcpRecord& out, std::string& error);

// Add an ACP to a target element (`target_kind == "element"`) or relationship
// (`target_kind == "relationship"`). The id is generated by the underlying
// mutator on first apply and captured into the audit payload; on replay it is
// forced via `core::acp::AddAcpWithId`.
class AddAcpCommand final : public ICommand {
public:
    AddAcpCommand(std::string target_kind, std::string target_id)
        : target_kind_(std::move(target_kind)), target_id_(std::move(target_id)) {}

    std::string Name() const override { return "AddAcp"; }
    bool        Apply(CommandContext& ctx, audit::AuditEvent& out_event, std::string& out_error) override;

    const std::string& GeneratedAcpId() const { return generated_acp_id_; }

private:
    std::string target_kind_;
    std::string target_id_;
    std::string generated_acp_id_;
};

// Remove an existing ACP by id.
class RemoveAcpCommand final : public ICommand {
public:
    explicit RemoveAcpCommand(std::string acp_id) : acp_id_(std::move(acp_id)) {}

    std::string Name() const override { return "RemoveAcp"; }
    bool        Apply(CommandContext& ctx, audit::AuditEvent& out_event, std::string& out_error) override;

private:
    std::string acp_id_;
};

// Insert or update an ACP record (edit name / resolution / target).
class UpsertAcpCommand final : public ICommand {
public:
    explicit UpsertAcpCommand(parser::AcpRecord acp) : acp_(std::move(acp)) {}

    std::string Name() const override { return "UpsertAcp"; }
    bool        Apply(CommandContext& ctx, audit::AuditEvent& out_event, std::string& out_error) override;

private:
    parser::AcpRecord acp_;
};

// Create a confidence argument tree (a confidence ArgumentPackage + top goal) for
// an existing ACP and link the ACP to it. The compound op generates exactly two
// ids -- the argument package and the top goal -- both captured into the audit
// payload; replay forces them via `core::acp::CreateConfidenceArgumentTreeForAcpWithIds`.
class CreateConfidenceArgumentTreeForAcpCommand final : public ICommand {
public:
    explicit CreateConfidenceArgumentTreeForAcpCommand(std::string acp_id) : acp_id_(std::move(acp_id)) {}

    std::string Name() const override { return "CreateConfidenceArgumentTree"; }
    bool        Apply(CommandContext& ctx, audit::AuditEvent& out_event, std::string& out_error) override;

    const std::string& AcpId() const { return acp_id_; }
    const std::string& GeneratedArgumentPackageId() const { return argument_package_id_; }
    const std::string& GeneratedTopGoalId() const { return top_goal_id_; }

private:
    std::string acp_id_;
    std::string argument_package_id_;
    std::string top_goal_id_;
};

} // namespace core::commands
