# --------------------------------------------------------------------
# write_build_id.cmake — stamp af-sccg-review-eval with `git describe`.
#
# Usage (from the af_build_id target, at build time):
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<header> [-DGIT_EXECUTABLE=<git>] -P cmake/write_build_id.cmake
#
# Run on every build rather than at configure time: an id captured at configure
# went stale with the next commit or checkout in the same build tree, and every
# record the harness wrote then named a build that had not produced it. The
# header is rewritten only when the id changes, so an unchanged tree rebuilds
# nothing.
# --------------------------------------------------------------------

set(build_id "unknown")
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --always --dirty --abbrev=12
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE described
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE described_result
        ERROR_QUIET
    )
    if(described_result EQUAL 0 AND NOT described STREQUAL "")
        set(build_id "${described}")
    endif()
endif()

set(content "// Generated by cmake/write_build_id.cmake at build time. Do not edit.\n#pragma once\n#define AF_BUILD_ID \"${build_id}\"\n")
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
